{% set name = "skyfield-data" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe3484028cf96eb8040104d0626ec712f73e22e0f97a1eee62527207eead66c8

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - skyfield_data

about:
  home: https://github.com/brunobord/skyfield-data
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Data files for Skyfield

extra:
  recipe-maintainers:
    - Matt-BF
    - ReimarBauer
